### ISSUE TITLE
Air Strike Patrol "Flickering Crushed Screen"

### ISSUE THREAD

**Issue by meepingsnesroms** [libretro/snes9x#64]
On mission briefing screens there is a flickering crushed overlay(it is the same image thats on the screen) on the top 1/4 of the screen.

This does not happen in snes9x2010.

RetroArch: 1.6.0 stable
Snes9x: 1.54.1 3fb8977
OS: Mac

**Comment by hizzlekizzle** [comment]
does it happen in upstream/standalone?

**Comment by meepingsnesroms** [comment]
I cant test it because the only non RetroArch build of 1.54.1 is for windows.

**Comment by nemo93** [comment]
I do confirm that it DOESN'T happen in upstream version. I've been unable to reproduce on Snes9x 1.54.1 - Windows x64.

**Comment by Oggom** [comment]
Known issue https://github.com/libretro/snes9x/issues/9

**Comment by kps501** [comment]
Still don't know exactly what triggers this. But interlace should draw at 30fps (after even + odd cycle). Retroarch is drawing both frames (pseudo-60) so we see that intermittent throwaway frame, which creates that flicker effect.

**Comment by kps501** [comment]
memmove error when switching on interlace mid-frame. It's fixed in latest nightly - no more flicker. Please test and close issue if confirm.
https://buildbot.libretro.com/nightly/

**Comment by Tatsuya79** [comment]
I can confirm it fixed here on win7 x64.

**Comment by meepingsnesroms** [comment]
Issue still exists:
![img_20180530_135243](https://user-images.githubusercontent.com/1220805/40747058-0e4ef9c2-6411-11e8-9e60-398acd6775ad.jpg)

Updated to latest nightly first, this is on Mac OS.

**Comment by kps501** [comment]
Hmm. Yeah, ASP was fixed as of May 29, 2018
https://github.com/libretro/snes9x/commit/58cfa63b899b48012b9aa29abca88dbf913affc2

Okay, thanks for mentioning this. Please keep us updated of Mac OS port, whenever update happens. :)

**Comment by meepingsnesroms** [comment]
Mac OS build is up, this bug is fully fixed.
